In [2]:
import tensorflow as tf
print("Tenserflow version : {}".format(tf.__version__))
print("Eager execution is : {}".format(tf.executing_eagerly()))
print("Keras version: {}".format(tf.keras.__version__))

Tenserflow version : 2.12.0
Eager execution is : True
Keras version: 2.12.0


# Tensor Constant

In [3]:
ineuron = tf.constant(42)
ineuron

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
ineuron.numpy()

42

In [5]:
ineuron1 = tf.constant(1, dtype=tf.int64)
ineuron1.numpy()

1

In [6]:
ineuron_x = tf.constant([[4,2],[9,5]])
print(ineuron_x)

tf.Tensor(
[[4 2]
 [9 5]], shape=(2, 2), dtype=int32)


In [7]:
ineuron_x.numpy()

array([[4, 2],
       [9, 5]], dtype=int32)

In [8]:
print("shape:",ineuron_x.shape)

shape: (2, 2)


# Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [9]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [10]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [11]:
import tensorflow as tf
const2 = tf.constant([[3,4,5],[3,4,5]])
const1 = tf.constant([[1,2,3],[1,2,3]])
result = tf.add(const1, const2)
print(result)

tf.Tensor(
[[4 6 8]
 [4 6 8]], shape=(2, 3), dtype=int32)


# Random Constant

In [12]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.02385941, -0.47804123],
       [ 0.38087028, -0.6817273 ]], dtype=float32)>

In [13]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 4],
       [6, 1]], dtype=int32)>

# Declaring Variables

In [14]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0.,1.,2.],[3.,4.,5.] ],[ [6.,7.,8.], [9.,10.,11.] ] ]) # rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

## The datatype can be explicitly specified

In [15]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

In [16]:
var_ressign = tf.Variable(89.)
var_ressign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [17]:
initial_value =tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.18965125,  0.6074741 ],
       [ 0.35533696, -0.8598548 ]], dtype=float32)>


In [18]:
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [19]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j]+added_value[i,j]

# Shaping a tensor

In [20]:
tensor = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


#### Tensors may be reshaped and retain the same values, as is often required for constructing neural networks.


In [21]:
tensor1 = tf.reshape(tensor,[2,6]) # 2 rows 6 cols
tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [22]:
tensor2 = tf.reshape(tensor,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]],
      dtype=float32)>

### Ranking (dimensions) of a tensor

In [23]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### Specifying an element of a tensor

In [24]:
tensor3 = tensor[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

#### Casting a tensor to a NumPy/Python variable

In [25]:
print(tensor.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [26]:
print(tensor[1, 0, 2].numpy())

8.0


#### Finding the size (number of elements) of a tensor

In [27]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

In [28]:
#the datatype of a tensor
tensor3.dtype

tf.float32

### Tensorflow mathematical operations
>Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.


In [29]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 0.71086794  0.06884045]
 [ 0.97688717 -1.2031217 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.13599163 -1.9232765 ]
 [ 0.5944515  -0.2348423 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.5748763 -1.854436 ]
 [ 1.5713387 -1.437964 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.33048278 3.4389331 ]
 [2.4691052  2.0677404 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7769108  0.1565412 ]
 [4.813087   0.23741065]], shape=(2, 2), dtype=float32)


### Performing element-wise primitive tensor operations

In [30]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

### Broadcasting
>Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

>The simplest example is that of multiplying a tensor by a scalar:

In [31]:
tensor4 = tensor*4
print(tensor4)

tf.Tensor(
[[[ 0.  4.  8.]
  [12. 16. 20.]]

 [[24. 28. 32.]
  [36. 40. 44.]]], shape=(2, 2, 3), dtype=float32)


### Transpose Matrix multiplication

In [32]:
matrix_u = tf.constant([[3,4,3]])
matrix_v = tf.constant([[1,2,1]])

tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[14]], dtype=int32)>

### Casting a tensor to another (tensor) datatype

In [33]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]], dtype=int32)>

### With truncation

In [34]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Declaring Ragged tensors

`A ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are dimensions that have slices that may have different lengths.There are a variety of methods for declaring ragged arrays, the simplest being a constant ragged
array.`

#### The following example shows how to declare a constant ragged array and the lengths of the individual slices:

In [35]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


### Finding the squared difference between two tensors

In [36]:
varx = [1,3,5,7,11]
vary = 5
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

#### Finding the mean

>The following is the signature of
>tf.reduce_mean().

`Note that this is equivalent to np.mean, except that it infers the return datatype from the input tensor,
whereas np.mean allows you to specify the output type (defaulting to float64):`

`tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)`


In [37]:
#Defining a constant
numbers = tf.constant([[4., 5.], [7., 3.]])

#### Find the mean across all axes (use the default axis = None)



In [38]:
tf.reduce_mean(input_tensor=numbers)
#( 4. + 5. + 7. + 3.)/4 = 4.75

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

#### Find the mean across columns (that is, reduce rows) with this:

In [40]:
tf.reduce_mean(input_tensor=numbers, axis=0) # [ (4. + 7. )/2 , (5. + 3.)/2 ] = [5.5, 4.]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

#### When keepdims is True, the reduced axis is retained with a length of 1:

In [41]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5.5, 4. ]], dtype=float32)>

#### Find the mean across rows (that is, reduce columns) with this:

In [42]:
tf.reduce_mean(input_tensor=numbers, axis=1) # [ (4. + 5. )/2 , (7. + 3. )/2] = [4.5, 5]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

#### When keepdims is True, the reduced axis is retained with a length of 1:

In [43]:
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[4.5],
       [5. ]], dtype=float32)>

#### Generating tensors filled with random values

##### Using tf.random.normal()

>tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

>The required signature is as follows:
    
>tf. random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

In [44]:
tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None, name=None)
ran = tf.random.normal(shape = (3,2), mean=10.0, stddev=2.0)
print(ran)

tf.Tensor(
[[ 5.9352217 11.231633 ]
 [12.685875   8.394974 ]
 [12.319219  11.94248  ]], shape=(3, 2), dtype=float32)


#### Using tf.random.uniform()

>The required signature is this:
    
>tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)

`This outputs a tensor of the given shape filled with values from a uniform distribution in the range
minval to maxval, where the lower bound is inclusive but the upper bound isn't.
Take this, for example:`

In [45]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.15795016, 0.9789971 , 0.574981  , 0.00581408],
       [0.42059004, 0.45045102, 0.61072814, 0.28582668]], dtype=float32)>

#### Setting the seed

In [47]:
tf.random.set_seed(11)
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1) #Call 1
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


In [48]:
tf.random.set_seed(11) #same seed
ran1 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
ran2 = tf.random.uniform(shape = (2,2), maxval=10, dtype = tf.int32)
print(ran1) #Call 2
print(ran2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


#### Practical example of Random values using Dices

In [49]:
dice1 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform([10, 1], minval=1, maxval=7, dtype=tf.int32))
# We may add dice1 and dice2 since they share the same shape and size.
dice_sum = dice1 + dice2
# We've got three separate 10x1 matrices. To produce a single
# 10x3 matrix, we'll concatenate them along dimension 1.
resulting_matrix = tf.concat(values=[dice1, dice2, dice_sum], axis=1)
print(resulting_matrix)

tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


#### Finding the indices of the largest and smallest element

>The signatures of the functions are as follows:
    
>`tf.argmax(input, axis=None, name=None, output_type=tf.int64 )`

>`tf.argmin(input, axis=None, name=None, output_type=tf.int64 )`

In [50]:
# 1-D tensor
t5 = tf.constant([2, 11, 5, 42, 7, 19, -6, -11, 29])
print(t5)


i = tf.argmax(input=t5)
print('index of max; ', i)
print('Max element: ',t5[i].numpy())


i = tf.argmin(input=t5,axis=0).numpy()
print('index of min: ', i)
print('Min element: ',t5[i].numpy())


t6 = tf.reshape(t5, [3,3])
print(t6)


i = tf.argmax(input=t6,axis=0).numpy() # max arg down rows
print('indices of max down rows; ', i)

i = tf.argmin(input=t6,axis=0).numpy() # min arg down rows
print('indices of min down rows ; ',i)
print(t6)

i = tf.argmax(input=t6,axis=1).numpy() # max arg across cols
print('indices of max across cols: ',i)

i = tf.argmin(input=t6,axis=1).numpy() # min arg across cols
print('indices of min across cols: ',i)


tf.Tensor([  2  11   5  42   7  19  -6 -11  29], shape=(9,), dtype=int32)
index of max;  tf.Tensor(3, shape=(), dtype=int64)
Max element:  42
index of min:  7
Min element:  -11
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max down rows;  [1 0 2]
indices of min down rows ;  [2 2 0]
tf.Tensor(
[[  2  11   5]
 [ 42   7  19]
 [ -6 -11  29]], shape=(3, 3), dtype=int32)
indices of max across cols:  [1 0 2]
indices of min across cols:  [0 1 1]


#### Saving and restoring tensor values using a checkpoint

In [51]:
variable = tf.Variable([[1,3,5,7],[11,13,17,19]])
checkpoint= tf.train.Checkpoint(var=variable)
save_path = checkpoint.save('./vars')
variable.assign([[0,0,0,0],[0,0,0,0]])
variable
checkpoint.restore(save_path)
print(variable)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [11, 13, 17, 19]], dtype=int32)>


#### Using tf.function

`tf.function is a function that will take a Python function and return a TensorFlow graph. The
advantage of this is that graphs can apply optimizations and exploit parallelism in the Python
function (func). tf.function is new to TensorFlow 2.`


>Its signature is as follows:
    
`tf.function(
func=None,
input_signature=None,
autograph=True,
experimental_autograph_options=None
)`


In [52]:
def f1(x, y):
    return tf.reduce_mean(input_tensor=tf.multiply(x ** 2, 5) + y**2)

f2 = tf.function(f1)
x = tf.constant([4., -5.])
y = tf.constant([2., 3.])

# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == f2(x,y).numpy()
#The assert passes, so there is no output

## Calculate the gradient

### GradientTape

>Another difference from numpy is that it can automatically track the gradient of any variable.

>Open one GradientTape and `tape.watch()` track variables through

In [54]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


>For all variables, the calculation is tracked by default and used to find the gradient, so do not `usetape.watch()`

In [55]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+tf.square(b))
    dc_da = tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[-0.469929    0.89920384]
 [-0.66446567 -0.79767007]], shape=(2, 2), dtype=float32)


> You can GradientTapefind higher-order derivatives by opening a few more:

In [56]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.4264985  0.6867533 ]
 [0.44663432 0.5015956 ]], shape=(2, 2), dtype=float32)


## The Keras Sequential model

`To build a Keras Sequential model, you add layers to it in the same order that you want the
computations to be undertaken by the network.`

`After you have built your model, you compile it; this optimizes the computations that are to be
undertaken, and is where you allocate the optimizer and the loss function you want your model to
use.`

`The next stage is to fit the model to the data. This is commonly known as training the model, and is
where all the computations take place. It is possible to present the data to the model either in
batches, or all at once.`

`Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having
trained your model, you can use it to make predictions on new data. So, the workflow is: build,
compile, fit, evaluate, make predictions.`
`There are two ways to create a Sequential model. Let's take a look at each of them.`

### The first way to create a Sequential model

`Firstly, you can pass a list of layer instances to the constructor, as in the following example.
For now, we will just explain enough to allow you to understand what is happening here.`

`Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every
individual data point is an unsigned 8-bit integer (uint8), as are the labels:`

#### Loading the datset

In [57]:
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


#### Definning the variables

In [58]:
epochs=10
batch_size = 32 # 32 is default in fit method but specify anyway

>Next, normalize all the data points (x) to be in the float range zero to one, and of the float32 type.

>Also, cast the labels (y) to int64, as required:

In [59]:
train_x, test_x = tf.cast(train_x/255.0, tf.float32), tf.cast(test_x/255.0, tf.float32)
train_y, test_y = tf.cast(train_y,tf.int64),tf.cast(test_y,tf.int64)

#### Building the Architecture

In [60]:
mnistmodel1 = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(512,activation=tf.nn.relu),
tf.keras.layers.Dropout(0.2),
tf.keras.layers.Dense(10,activation=tf.nn.softmax)
])


#### Compiling the model

In [61]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

#### Fitting the model

In [62]:
mnistmodel1.fit(train_x, train_y, batch_size=32, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 19s 9ms/step - loss: 0.2212 - accuracy: 0.9348
Epoch 2/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.0973 - accuracy: 0.9703
Epoch 3/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0686 - accuracy: 0.9782
Epoch 4/5
1875/1875 [==============================] - 14s 8ms/step - loss: 0.0534 - accuracy: 0.9832
Epoch 5/5
1875/1875 [==============================] - 16s 8ms/step - loss: 0.0432 - accuracy: 0.9856


#### Evaluate the mnistmodel1

In [63]:
mnistmodel1.evaluate(test_x, test_y)

313/313 [==============================] - 2s 6ms/step - loss: 0.0630 - accuracy: 0.9815


[0.06304460763931274, 0.9815000295639038]

>This represents a loss of 0.09 and an accuracy of 0.9801 on the test data.

>An accuracy of 0.98 means that out of 100 test data points, 98 were, on average, correctly identified by the model.

The second way to create a Sequential model

---


The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:



#### Building the Architecture & Compiling

In [65]:
mnistmodel2 = tf.keras.models.Sequential();
mnistmodel2.add(tf.keras.layers.Flatten())
mnistmodel2.add(tf.keras.layers.Dense(512, activation='relu'))
mnistmodel2.add(tf.keras.layers.Dropout(0.2))
mnistmodel2.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax))
mnistmodel2.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])

#### Fitting the mnistmodel2

In [66]:
mnistmodel2.fit(train_x, train_y, batch_size=64, epochs=5)

Epoch 1/5
938/938 [==============================] - 10s 10ms/step - loss: 0.2457 - accuracy: 0.9281
Epoch 2/5
938/938 [==============================] - 9s 9ms/step - loss: 0.1053 - accuracy: 0.9682
Epoch 3/5
938/938 [==============================] - 10s 11ms/step - loss: 0.0731 - accuracy: 0.9776
Epoch 4/5
938/938 [==============================] - 10s 11ms/step - loss: 0.0556 - accuracy: 0.9826
Epoch 5/5
938/938 [==============================] - 8s 9ms/step - loss: 0.0440 - accuracy: 0.9858


#### Evaluate the mnistmodel2

In [67]:
mnistmodel2.evaluate(test_x, test_y)

313/313 [==============================] - 1s 3ms/step - loss: 0.0625 - accuracy: 0.9812


[0.06247418373823166, 0.9811999797821045]

### The Keras functional API

`The functional API lets you build much more complex architectures than the simple linear stack of
Sequential models we have seen previously. It also supports more advanced models. These models
include multi-input and multi-output models, models with shared layers, and models with residual
connections.`

`Here is a short example, with an identical architecture to the previous two, of the use of the
functional API.`

In [68]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(train_x,train_y), (test_x, test_y) = mnist.load_data()

train_x, test_x = train_x/255.0, test_x/255.0

epochs=10


#### Building the Architecture

In [69]:
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel3 = tf.keras.Model(inputs=inputs, outputs=predictions)

#### Compile & Fit

In [70]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel3.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel3.fit(train_x, train_y, batch_size=32, epochs=epochs)

Epoch 1/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.2198 - accuracy: 0.9358
Epoch 2/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0958 - accuracy: 0.9706
Epoch 3/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0684 - accuracy: 0.9780
Epoch 4/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0539 - accuracy: 0.9822
Epoch 5/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0434 - accuracy: 0.9857
Epoch 6/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.0347 - accuracy: 0.9886
Epoch 7/10
1875/1875 [==============================] - 14s 8ms/step - loss: 0.0301 - accuracy: 0.9900
Epoch 8/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0279 - accuracy: 0.9909
Epoch 9/10
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0246 - accuracy: 0.9915
Epoch 10/10
1875/1875 [==============================] - 14s 8ms/step - 

#### Evaluate the mnistmodel3

In [71]:
mnistmodel3.evaluate(test_x, test_y)

313/313 [==============================] - 1s 3ms/step - loss: 0.0802 - accuracy: 0.9813


[0.08017457276582718, 0.9812999963760376]

### Subclassing the Keras Model class

In [72]:
import tensorflow as tf

#### Building the subclass architecture

In [73]:
class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [74]:
mnistmodel4 = MNISTModel()

#### Compile & Fit

In [75]:
batch_size = 32
steps_per_epoch = len(train_x)//batch_size
print(steps_per_epoch)
mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

1875
Epoch 1/10
1875/1875 [==============================] - 17s 8ms/step - loss: 0.2191 - accuracy: 0.9348
Epoch 2/10
1875/1875 [==============================] - 17s 9ms/step - loss: 0.0958 - accuracy: 0.9709
Epoch 3/10
1875/1875 [==============================] - 16s 8ms/step - loss: 0.0688 - accuracy: 0.9785
Epoch 4/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0541 - accuracy: 0.9826
Epoch 5/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0444 - accuracy: 0.9850
Epoch 6/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0354 - accuracy: 0.9882
Epoch 7/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0316 - accuracy: 0.9892
Epoch 8/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0278 - accuracy: 0.9907
Epoch 9/10
1875/1875 [==============================] - 15s 8ms/step - loss: 0.0248 - accuracy: 0.9917
Epoch 10/10
1875/1875 [==============================] - 15s 8ms/ste

#### Evaluate the mnistmodel4

In [76]:
mnistmodel4.evaluate(test_x, test_y)

313/313 [==============================] - 1s 3ms/step - loss: 0.0716 - accuracy: 0.9811


[0.07157038897275925, 0.9811000227928162]