In [2]:
import numpy as np

In [3]:
l=[1,2,3,4,5]

In [4]:
arr=np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1=np.array([[1,2,3],[2,3,4]])

In [8]:
arr.ndim

1

In [9]:
arr1.ndim

2

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [19]:
mat=np.matrix(l)

In [20]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [21]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
a= arr

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[0]= 100

In [27]:
arr

array([100,   2,   3,   4,   5])

In [28]:
a

array([100,   2,   3,   4,   5])

In [29]:
b= np.copy(arr)

In [31]:
b[0]=234

In [32]:
b

array([234,   2,   3,   4,   5])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [38]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [39]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [42]:
iterable= (i*i for i in range(5))

In [44]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [46]:
np.fromstring('23 45 56',sep = ' ')

array([23., 45., 56.])

In [48]:
np.fromstring('23,45,56',sep=',')

array([23., 45., 56.])

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
arr.ndim

1

In [13]:
arr1.ndim

2

In [14]:
arr.size

5

In [15]:
arr1.size

6

In [16]:
arr.shape

(5,)

In [17]:
arr1.shape

(2, 3)

In [18]:
arr.dtype

dtype('int64')

In [19]:
arr1.dtype

dtype('int64')