In [1]:
#Sort, Search & Counting Function.

In [2]:
import numpy as np

In [8]:
arr=np.array([4,2,8,5,3,9,12,56])

In [9]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [10]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [11]:
np.searchsorted(arr,6)

5

In [13]:
arr1=np.array([0,324,645,65,6,6,0,0,0,234])

In [15]:
np.count_nonzero(arr1)

6

In [16]:
np.where(arr1>0)

(array([1, 2, 3, 4, 5, 9]),)

In [19]:
np.extract(arr1>2,arr1)

array([324, 645,  65,   6,   6, 234])

In [20]:
#Numpy - Byte Swapping.

In [21]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [25]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [26]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [27]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [28]:
#Numpy - Copies & Views.

In [29]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [30]:
a= np.copy(arr1)

In [31]:
b= arr1.view()

In [32]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [33]:
b[0]= 234

In [34]:
b

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [35]:
arr1

array([234, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [36]:
#Numpy - Matrix Library.

In [37]:
import numpy.matlib as nm

In [38]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [41]:
#Numpy - Linear Algebra

In [44]:
arr1=np.random.randint([[2,3],[4,5]])

In [46]:
arr2=np.random.randint([[5,3],[2,5]])

In [47]:
arr1

array([[0, 2],
       [0, 3]])

In [48]:
arr2

array([[1, 1],
       [0, 1]])

In [49]:
np.dot(arr1,arr2)

array([[0, 2],
       [0, 3]])

In [50]:
arr1@arr2

array([[0, 2],
       [0, 3]])