In [3]:
import numpy as np

In [2]:
#Numpy - Array Mainpulation.

In [2]:
arr=np.random.randint(1,10,(4,4))

In [3]:
arr

array([[3, 4, 8, 1],
       [7, 2, 4, 5],
       [7, 8, 6, 1],
       [7, 3, 8, 5]])

In [4]:
arr.reshape(8,2)

array([[3, 4],
       [8, 1],
       [7, 2],
       [4, 5],
       [7, 8],
       [6, 1],
       [7, 3],
       [8, 5]])

In [5]:
arr

array([[3, 4, 8, 1],
       [7, 2, 4, 5],
       [7, 8, 6, 1],
       [7, 3, 8, 5]])

In [6]:
arr.T

array([[3, 7, 7, 7],
       [4, 2, 8, 3],
       [8, 4, 6, 8],
       [1, 5, 1, 5]])

In [7]:
arr.flatten()

array([3, 4, 8, 1, 7, 2, 4, 5, 7, 8, 6, 1, 7, 3, 8, 5])

In [8]:
arr

array([[3, 4, 8, 1],
       [7, 2, 4, 5],
       [7, 8, 6, 1],
       [7, 3, 8, 5]])

In [11]:
np.expand_dims(arr,axis=1)

array([[[3, 4, 8, 1]],

       [[7, 2, 4, 5]],

       [[7, 8, 6, 1]],

       [[7, 3, 8, 5]]])

In [12]:
np.expand_dims(arr,axis=0)

array([[[3, 4, 8, 1],
        [7, 2, 4, 5],
        [7, 8, 6, 1],
        [7, 3, 8, 5]]])

In [13]:
data= np.array([[1],[2],[3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [17]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [18]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
#Numpy - Binary Operators.

In [4]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [21]:
arr1

array([[7, 5, 9, 7],
       [8, 9, 7, 4],
       [2, 5, 8, 4]])

In [22]:
arr2

array([[7, 3, 5, 1],
       [7, 5, 4, 6],
       [5, 8, 1, 2]])

In [23]:
arr1+arr2

array([[14,  8, 14,  8],
       [15, 14, 11, 10],
       [ 7, 13,  9,  6]])

In [24]:
arr1/arr2

array([[1.        , 1.66666667, 1.8       , 7.        ],
       [1.14285714, 1.8       , 1.75      , 0.66666667],
       [0.4       , 0.625     , 8.        , 2.        ]])

In [25]:
arr1*arr2

array([[49, 15, 45,  7],
       [56, 45, 28, 24],
       [10, 40,  8,  8]])

In [26]:
arr1-arr2

array([[ 0,  2,  4,  6],
       [ 1,  4,  3, -2],
       [-3, -3,  7,  2]])

In [27]:
arr1**arr2

array([[ 823543,     125,   59049,       7],
       [2097152,   59049,    2401,    4096],
       [     32,  390625,       8,      16]])

In [28]:
~arr1

array([[ -8,  -6, -10,  -8],
       [ -9, -10,  -8,  -5],
       [ -3,  -6,  -9,  -5]])

In [29]:
arr1

array([[7, 5, 9, 7],
       [8, 9, 7, 4],
       [2, 5, 8, 4]])

In [30]:
arr1>arr2

array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True]])

In [31]:
#Numpy - String Functions.

In [32]:
arr = np.array(['Amaan','raja'])

In [33]:
arr

array(['Amaan', 'raja'], dtype='<U5')

In [34]:
np.char.upper(arr)

array(['AMAAN', 'RAJA'], dtype='<U5')

In [35]:
np.char.capitalize(arr)

array(['Amaan', 'Raja'], dtype='<U5')

In [36]:
np.char.title(arr)

array(['Amaan', 'Raja'], dtype='<U5')

In [37]:
#Numpy -  Mathematical Funtions.

In [38]:
arr1

array([[7, 5, 9, 7],
       [8, 9, 7, 4],
       [2, 5, 8, 4]])

In [39]:
np.sin(arr1)

array([[ 0.6569866 , -0.95892427,  0.41211849,  0.6569866 ],
       [ 0.98935825,  0.41211849,  0.6569866 , -0.7568025 ],
       [ 0.90929743, -0.95892427,  0.98935825, -0.7568025 ]])

In [40]:
np.cos(arr1)

array([[ 0.75390225,  0.28366219, -0.91113026,  0.75390225],
       [-0.14550003, -0.91113026,  0.75390225, -0.65364362],
       [-0.41614684,  0.28366219, -0.14550003, -0.65364362]])

In [41]:
np.tan(arr1)

array([[ 0.87144798, -3.38051501, -0.45231566,  0.87144798],
       [-6.79971146, -0.45231566,  0.87144798,  1.15782128],
       [-2.18503986, -3.38051501, -6.79971146,  1.15782128]])

In [42]:
np.log(arr1)

array([[1.94591015, 1.60943791, 2.19722458, 1.94591015],
       [2.07944154, 2.19722458, 1.94591015, 1.38629436],
       [0.69314718, 1.60943791, 2.07944154, 1.38629436]])

In [43]:
np.exp(arr1)

array([[1.09663316e+03, 1.48413159e+02, 8.10308393e+03, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 1.09663316e+03, 5.45981500e+01],
       [7.38905610e+00, 1.48413159e+02, 2.98095799e+03, 5.45981500e+01]])

In [44]:
np.power(arr1,2)

array([[49, 25, 81, 49],
       [64, 81, 49, 16],
       [ 4, 25, 64, 16]])

In [45]:
np.mean(arr1)

6.25

In [46]:
np.median(arr1)

7.0

In [48]:
np.std(arr1)

2.1262251370288454

In [49]:
np.var(arr1)

4.520833333333333

In [50]:
np.min(arr1)

2

In [51]:
np.max(arr1)

9

In [52]:
#Numpy - Arthemetic Operations.

In [53]:
arr1

array([[7, 5, 9, 7],
       [8, 9, 7, 4],
       [2, 5, 8, 4]])

In [54]:
arr2

array([[7, 3, 5, 1],
       [7, 5, 4, 6],
       [5, 8, 1, 2]])

In [55]:
arr1-arr2

array([[ 0,  2,  4,  6],
       [ 1,  4,  3, -2],
       [-3, -3,  7,  2]])

In [56]:
np.subtract(arr1,arr2)

array([[ 0,  2,  4,  6],
       [ 1,  4,  3, -2],
       [-3, -3,  7,  2]])

In [57]:
np.multiply(arr1,arr2)

array([[49, 15, 45,  7],
       [56, 45, 28, 24],
       [10, 40,  8,  8]])

In [58]:
np.mod(arr1,arr2)

array([[0, 2, 4, 0],
       [1, 4, 3, 4],
       [2, 5, 0, 0]])

In [59]:
np.power(arr1,arr2)

array([[ 823543,     125,   59049,       7],
       [2097152,   59049,    2401,    4096],
       [     32,  390625,       8,      16]])

In [60]:
np.sqrt(arr1)

array([[2.64575131, 2.23606798, 3.        , 2.64575131],
       [2.82842712, 3.        , 2.64575131, 2.        ],
       [1.41421356, 2.23606798, 2.82842712, 2.        ]])

In [1]:
#Numpy - Statistical Funtions.

In [5]:
arr1

array([[5, 6, 9, 7],
       [3, 9, 8, 2],
       [8, 8, 1, 4]])

In [7]:
np.mean(arr1)

5.833333333333333

In [8]:
np.std(arr1)

2.6718699236468995

In [9]:
np.median(arr1)

6.5